var AllianceNames = [
'Dark Malice',
'Dreadful Under',
'Restless War',
'Royal Banda',
'The Encore',
'SUMMONERS',
'The Six Cheez',
'Exitium Town',
'Giant Legion',
'VOIDWALKERS',
'The Xxelitexx',
'Holy Brigade',
'The Bracelet',
'The Pheonix',
'The Samurai',
'Metal Azeroth',
'Chaotic Clan',
'Gnoman Calls',
'Pavor Knights',
'Sere Lions',
'The Pryde',
'PROPHETICS',
'TYRANNY',
'The Twink',
'The Pally Fury',
'Forsaken Order',
'GANKSTARZ',
'Hit Bliss',
'HORDE',
'The Stockades',
'The Caballeros',
'VENOM',
'Pwnage Flames',
'Wicked Dragons',
'ANAMANIACS',
'REVELATIONISTS',
'Gnomish Blade',
'Angry Foos',
'The Evul',
'The Azeroth',
'The Devil',
'Divine Amicus',
'The Destroyers',
'The Agony',
'Outer Girls',
'NIGHTWOLV',
'FALLEN'
 ];
